### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by sdmit93** [Mahmoudz/Porto#15]
Hello!
Porto, that's really awesome. I really intresting make my future web app on this architectural pattern. But I have some questions, I hope you'll finf time to answer on thats.

1. If I will use for example Cookie (from laravel) or GuzzleHttp, do I need  to create Abstract Classes for it in the Core and after that create in the Ship layer some folders (Other Folders) and use classes from this folders in Containers? Or do I need to create Abstract Classes in the Core and extends thats in components Cookie and HttpClien in folder Parents in the Ship layer and after that use components (Cookie and HttpClien) in Containers?

2. I found that in apiato/app/Containers/Authentication/UI/API/Controllers/Controller.php you use Facade to access to Cookie, why it did't moved to the Ship layer in the Core in Abstract Classes? Should I move any connection with the infrastructure (frameworks, composer packages) to the core in Abstract Classes or I can use Facades and Contracts in containers?

3. If I'll create dashboard in my application do I need to create UI - Admin?

**Comment by Mahmoudz** [comment]
Hi @sdmit93, thank you for the message. 

1. Depend on how much separation you need and why you need it. I'd suggest going with the faster solution first "no abstracts", and only refactor when needed.

2. Facade in general isn't a bad pattern in my opinion, but consistency is a important, I think we need to refactor the code hopefully soon. I guess it's optional again to use those Laravel default Facade in your code or abstract them. 

3. If you're Dashboard App isn't API based you can do that, but it's always better to make an API for your Dashboard app and consume it from a separate JS app. 

Hope I answered your questions.
