### ISSUE TITLE
Can route call controller in another container?

### ISSUE THREAD

**Issue by xyluet** [Mahmoudz/Porto#21]
For real problem I have 2 tables `district` and `sub_district`.

I've following routes
- `/districts`
- `/districts/{id}/sub-districts`
- `/sub-districts`

I've containers `District` and `SubDistrict`.

In `/districts/{id}/sub-districts`, where do I have controller function named `getSubDistrictsByDistrictId` ? In `District` or `SubDistrict` container?

Fow now I put that function in `SubDistrict` container, But it makes me to call controller from different container.

**Comment by Takitaf** [comment]
Containers in fact depends on business logic, not on the tables in database. Not every entity in database should have very own Container. First question is: "would `SubDistricts` have totally different logic from `Districts`"? 
If not, I would probably put `SubDistricts` into `District` container, as they will have much in common. 
If it would have different logic however, then maybe `Action` that loads `SubDistrictsByDistrictId` should be in `SubDistrict` container also, so the `SubDistrict` controller can call `Action` from its container?

The hardest thing is to keep containers "balanced" - they easily becoming either too small and too distributed, or too big and there are too many actions inside one container.

**Comment by xyluet** [comment]
Yes they have different logic

In short, from container `A` route, can I call controller in container `B`?
OR
I have to make function in `A` controller and call action in container `B`?

bcs in the end both will call action in container `B`
