### ISSUE TITLE
Can I register a different container's task with the provider?

### ISSUE THREAD

**Issue by cherryred5959** [Mahmoudz/Porto#24]
I had one question when I registered the components of that container in the main provider.

The 'Poto' architecture said, action can call the tasks of other containers.

I don't think we can guarantee the order in which to register actions that are dependent on other container tasks from the certain container provider.  

I've been looking at an example called apiato, but it's not very helpful because it's.

Is my approach wrong?
Or are there any solutions to this?

**Comment by cherryred5959** [comment]
I tried to think more about this, but I think it is correct to register the action in 'boot'.

**Comment by Mahmoudz** [comment]
@cherryred5959 If it feels correct then it's most likely correct. As long as you maintain consistency.
