### ISSUE TITLE
Mention laravel-modules package

### ISSUE THREAD

**Issue by itailulu** [Mahmoudz/Porto#37]
@Mahmoudz Very interesting read.
It might be worth mentioning [laravel-modules](https://github.com/nWidart/laravel-modules) package on your references.

**Comment by Mohammad-Alavi** [comment]
@itailulu Nice package! We have something like that in [Apiato](https://github.com/apiato/apiato) (a Porto implementation by creator of Porto). It is called [Container Installer](https://github.com/apiato/container-installer).
