### ISSUE TITLE
Actions, SubActions, Tasks re-usability issue

### ISSUE THREAD

**Issue by timurlan156** [Mahmoudz/Porto#38]
There are so many cases when I have a beautiful class `MyFirstTask.php`. And also I have `MySecondTask.php` which I use in some SubAction classes. And I really need (but unfortunately **Should not**) to use `MyFirstTask.php` in `MySecondTask.php` that would perfectly solve everything and rescue the world. What should I do in such multiple cases when I really need to re-use Tasks (or SubActions, or Actions) in similar kind of classes (Tasks in Tasks etc)? Also sometimes there's one super useful SubAction class that would perfectly solve many problems in a Task class.

**Comment by indigoram89** [comment]
Great question +1

**Comment by Mohammad-Alavi** [comment]
A `task` should only have 1 job. If it has more than 1 job (e.g. needs to use another `task`) then it should be either an `action` or a `subAction` IMO.

**Comment by Mohammad-Alavi** [comment]
What is preventing you from using a `task` in multiple `subAction`s? Is there any rule against this? If there is, I can't find it. I do this regularly.
