### ISSUE TITLE
Any success stories?

### ISSUE THREAD

**Issue by gelinger777** [Mahmoudz/Porto#41]
First of all thank you very much for a very detailed explaination of the approach you propose. I wonder if you have already a list of some big projects who has successfully implemented Porto and also Apiary?

**Comment by Mohammad-Alavi** [comment]
I am using Apiato for all my projects for years now. It works like a charm. Ill never go back to using Laravel without Apiato.
If you want to know more you can join [Apiato's Discord Server](https://discord.com/invite/ryPcV4KM5k) and ask about other Apiato user experiences there.
